# Generated by Django 4.1.3 on 2022-11-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(db_column='ID_CATEGORIA', primary_key=True, serialize=False)),
                ('nombre_categoria', models.TextField(blank=True, db_column='NOMBRE_CATEGORIA', null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comment', models.AutoField(db_column='ID_COMMENT', primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, db_column='COMMENT', max_length=50, null=True)),
            ],
            options={
                'db_table': 'comentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallecomentario',
            fields=[
                ('id_detacomme', models.AutoField(db_column='ID_DETACOMME', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detallecomentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Falcultad',
            fields=[
                ('id_facultad', models.IntegerField(db_column='ID_FACULTAD', primary_key=True, serialize=False)),
                ('nombre_facultad', models.TextField(blank=True, db_column='NOMBRE_FACULTAD', null=True)),
            ],
            options={
                'db_table': 'falcultad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id_favorito', models.CharField(db_column='ID_FAVORITO', max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='TITULO', max_length=50)),
            ],
            options={
                'db_table': 'favoritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id_foto', models.IntegerField(db_column='ID_FOTO', primary_key=True, serialize=False)),
                ('ruta', models.TextField(blank=True, db_column='RUTA', null=True)),
            ],
            options={
                'db_table': 'foto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(db_column='ID_PRODUCTO', primary_key=True, serialize=False)),
                ('nombres', models.TextField(blank=True, db_column='NOMBRES', null=True)),
                ('cantidad_disponible', models.IntegerField(blank=True, db_column='CANTIDAD_DISPONIBLE', null=True)),
                ('precio', models.DecimalField(blank=True, db_column='PRECIO', decimal_places=0, max_digits=10, null=True)),
                ('estado_producto', models.TextField(blank=True, db_column='ESTADO_PRODUCTO', null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.IntegerField(db_column='ID_PUBLICACION', primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateField(blank=True, db_column='FECHA_PUBLICACION', null=True)),
                ('estado_publicacion', models.TextField(blank=True, db_column='ESTADO_PUBLICACION', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'publicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('carnet', models.IntegerField(db_column='CARNET', primary_key=True, serialize=False)),
                ('nombres', models.TextField(blank=True, db_column='NOMBRES', null=True)),
                ('correo_institucional', models.TextField(blank=True, db_column='CORREO_INSTITUCIONAL', null=True)),
                ('apellidos', models.TextField(blank=True, db_column='APELLIDOS', null=True)),
                ('estado', models.TextField(blank=True, db_column='ESTADO', null=True)),
                ('contrasena', models.TextField(blank=True, db_column='CONTRASENA', null=True)),
                ('numero_contacto', models.TextField(blank=True, db_column='NUMERO_CONTACTO', null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
