# Generated by Django 4.1.3 on 2022-11-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detallecomentario',
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
